### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by jubalh** [chickendude/Glossika-Android#1]
Would be cool to see a screenshot and maybe have an apk to download.

Non Android developer here, and curious if its worth the hassle to set up the environment ;)

**Comment by chickendude** [comment]
Hey jubalh, first off thanks for stopping by and showing interest! I've uplaoded a couple Youtube videos showing what it currently looks like:  
https://www.youtube.com/watch?v=xdW6S1pG2P8  
https://www.youtube.com/watch?v=Goup2gapa5A  

If you check the [releases](https://github.com/chickendude/Glossika-Android/releases) page you should find an apk to download the files. However, to actually use the app you'll need to create a .gls pack, either with the [scripts](https://github.com/chickendude/GlossikaNativeGLS) or by using the [online tool](https://ralena.ch). It's still early in development but once the database structure gets a bit more finalized i'll be putting it up on the Play Store.

Linking the videos and putting some screenshots in the readme is a good idea though, i'll get to work on that!

**Comment by jubalh** [comment]
It looks very nice! Great job @chickendude !
